"""add_alert_tables

Revision ID: 4a0032131db6
Revises: d5f8e9c1a2b3
Create Date: 2026-04-24 01:31:27.813138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4a0032131db6'
down_revision: Union[str, None] = 'd5f8e9c1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('operator', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('P0', 'P1', 'P2', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', name='alertrulestatus'), nullable=False),
    sa.Column('channels', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('suppress_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('auto_resolve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_name'), 'alert_rules', ['name'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('severity', sa.Enum('P0', 'P1', 'P2', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('FIRING', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED', name='alertstatus'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_table('alert_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_event_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WEBHOOK', 'PAGERDUTY', 'OPSGENIE', name='alertchannel'), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notifications_alert_event_id'), 'alert_notifications', ['alert_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_notifications_alert_event_id'), table_name='alert_notifications')
    op.drop_table('alert_notifications')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_alert_rules_name'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
