"""add memory tables

Revision ID: 648e66f44116
Revises: e57a18310e2b
Create Date: 2026-04-12 12:02:55.722657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = "648e66f44116"
down_revision: Union[str, None] = "e57a18310e2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_name", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("system_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("previous_system_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("confidence_threshold", sa.Float(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_configs_agent_name"), "agent_configs", ["agent_name"], unique=True
    )
    op.create_table(
        "interaction_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("summary_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resolved_intent", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("satisfaction_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interaction_summaries_thread_id"),
        "interaction_summaries",
        ["thread_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_summaries_user_id"), "interaction_summaries", ["user_id"], unique=False
    )
    op.create_table(
        "routing_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("intent_category", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("target_agent", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("condition_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routing_rules_intent_category"), "routing_rules", ["intent_category"], unique=False
    )
    op.create_table(
        "user_facts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fact_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_thread_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_facts_user_id"), "user_facts", ["user_id"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("preference_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("preference_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_preferences_user_id"), "user_preferences", ["user_id"], unique=False
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("membership_level", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column(
            "preferred_language", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("total_orders", sa.Integer(), nullable=False),
        sa.Column("lifetime_value", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_user_preferences_user_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_user_facts_user_id"), table_name="user_facts")
    op.drop_table("user_facts")
    op.drop_index(op.f("ix_routing_rules_intent_category"), table_name="routing_rules")
    op.drop_table("routing_rules")
    op.drop_index(op.f("ix_interaction_summaries_user_id"), table_name="interaction_summaries")
    op.drop_index(op.f("ix_interaction_summaries_thread_id"), table_name="interaction_summaries")
    op.drop_table("interaction_summaries")
    op.drop_index(op.f("ix_agent_configs_agent_name"), table_name="agent_configs")
    op.drop_table("agent_configs")
    # ### end Alembic commands ###
