"""add_order_delivered_at_and_fix_complaint_fk

Revision ID: add_order_delivered_at_and_fix_complaint_fk
Revises: 49f33c393451
Create Date: 2025-01-13 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "add_order_delivered_at_and_fix_complaint_fk"
down_revision: Union[str, None] = "49f33c393451"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add delivered_at column to orders table
    op.add_column("orders", sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True))

    # Add foreign key constraint to complaint_tickets.user_id
    op.create_foreign_key(
        "fk_complaint_tickets_user_id_users", "complaint_tickets", "users", ["user_id"], ["id"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign key constraint
    op.drop_constraint(
        "fk_complaint_tickets_user_id_users", "complaint_tickets", type_="foreignkey"
    )

    # Drop delivered_at column
    op.drop_column("orders", "delivered_at")

    # ### end Alembic commands ###
