"""add trace_id to graph_execution_logs

Revision ID: eda726e63e1d
Revises: 4a0032131db6
Create Date: 2026-04-24 16:01:27.310300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'eda726e63e1d'
down_revision: Union[str, None] = '4a0032131db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph_execution_logs', sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graph_execution_logs', 'trace_id')
    # ### end Alembic commands ###
