"""Generate few-shot examples for all agent types.

This script creates example files for each agent type to support
cross-agent few-shot learning as required by Task 2.8.
"""

import json
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent / "data" / "prompt_examples"


def write_examples(agent_type: str, examples: list[dict]) -> None:
    """Write examples to a JSONL file."""
    dir_path = BASE_DIR / agent_type
    dir_path.mkdir(parents=True, exist_ok=True)
    file_path = dir_path / "examples.jsonl"
    with open(file_path, "w", encoding="utf-8") as f:
        for ex in examples:
            f.write(json.dumps(ex, ensure_ascii=False) + "\n")
    print(f"Created {len(examples)} examples for {agent_type} at {file_path}")


# ---------------------------------------------------------------------------
# Order Agent Examples
# ---------------------------------------------------------------------------

ORDER_EXAMPLES = [
    {"query": "帮我查下订单 SN2024055 现在什么状态", "intent": "QUERY", "scenario": "order_status", "slots": {"order_sn": "SN2024055"}, "expected_response": "查询订单状态并告知用户"},
    {"query": "我昨天下的单发货了吗", "intent": "QUERY", "scenario": "shipping_status", "slots": {}, "expected_response": "查询最近订单的发货状态"},
    {"query": "订单号 SN2024099 的物流信息怎么查不到", "intent": "QUERY", "scenario": "logistics_issue", "slots": {"order_sn": "SN2024099"}, "expected_response": "解释可能原因并提供解决方案"},
    {"query": "我的订单显示已签收但我没收到", "intent": "QUERY", "scenario": "delivery_issue", "slots": {}, "expected_response": "核实签收信息并启动调查"},
    {"query": "帮我看看最近的订单", "intent": "QUERY", "scenario": "recent_orders", "slots": {}, "expected_response": "列出用户最近的订单列表"},
    {"query": "订单里买了什么，总价多少", "intent": "QUERY", "scenario": "order_details", "slots": {}, "expected_response": "提供订单商品明细和金额"},
    {"query": "SN2024111 什么时候能到", "intent": "QUERY", "scenario": "delivery_estimate", "slots": {"order_sn": "SN2024111"}, "expected_response": "提供预计送达时间"},
    {"query": "为什么我的订单被取消了", "intent": "QUERY", "scenario": "cancellation_reason", "slots": {}, "expected_response": "查询取消原因并解释"},
    {"query": "我想申请退货，订单 SN2024001", "intent": "REFUND", "scenario": "refund_request", "slots": {"order_sn": "SN2024001"}, "expected_response": "检查退货资格并处理申请"},
    {"query": "这个商品能退吗，昨天才买的", "intent": "REFUND", "scenario": "refund_eligibility", "slots": {}, "expected_response": "确认退货政策并告知资格"},
    {"query": "退货进度怎么样了", "intent": "REFUND", "scenario": "refund_status", "slots": {}, "expected_response": "查询退货处理进度"},
    {"query": "我不想退了，取消退货申请", "intent": "REFUND", "scenario": "cancel_refund", "slots": {}, "expected_response": "协助取消退货申请"},
    {"query": "订单已经付款了能改地址吗", "intent": "QUERY", "scenario": "modify_address", "slots": {}, "expected_response": "确认是否可修改收货地址"},
    {"query": "帮我取消还没发货的订单", "intent": "QUERY", "scenario": "cancel_order", "slots": {}, "expected_response": "查询并协助取消未发货订单"},
    {"query": "我想把订单里的一个商品退了", "intent": "REFUND", "scenario": "partial_refund", "slots": {}, "expected_response": "处理部分退货申请"},
    {"query": "这个订单用了优惠券，退货能退吗", "intent": "REFUND", "scenario": "refund_with_coupon", "slots": {}, "expected_response": "说明优惠券退款规则"},
    {"query": "订单金额不对，少了个折扣", "intent": "QUERY", "scenario": "price_discrepancy", "slots": {}, "expected_response": "核实订单金额和折扣"},
    {"query": "我下了两个订单能合并发货吗", "intent": "QUERY", "scenario": "merge_orders", "slots": {}, "expected_response": "确认是否支持合并发货"},
    {"query": "订单已经发货了还能改地址吗", "intent": "QUERY", "scenario": "change_address_shipped", "slots": {}, "expected_response": "说明发货后地址修改规则"},
    {"query": "为什么我的订单还在待处理", "intent": "QUERY", "scenario": "pending_status", "slots": {}, "expected_response": "解释订单处理流程和当前状态"},
    {"query": "帮我查下3月份的所有订单", "intent": "QUERY", "scenario": "historical_orders", "slots": {}, "expected_response": "按时间段查询订单列表"},
    {"query": "这个订单的发票怎么开", "intent": "QUERY", "scenario": "invoice_request", "slots": {}, "expected_response": "提供发票开具指引"},
    {"query": "我想把订单换成另一个颜色", "intent": "QUERY", "scenario": "modify_order", "slots": {}, "expected_response": "确认是否支持修改商品规格"},
    {"query": "订单里有个商品缺货了怎么办", "intent": "QUERY", "scenario": "out_of_stock", "slots": {}, "expected_response": "提供缺货处理方案"},
    {"query": "我的订单被拆分成两个包裹了", "intent": "QUERY", "scenario": "split_shipment", "slots": {}, "expected_response": "解释分包裹发货原因"},
    {"query": "帮我确认一下订单 SN2024333 的商品", "intent": "QUERY", "scenario": "confirm_items", "slots": {"order_sn": "SN2024333"}, "expected_response": "列出订单商品明细"},
    {"query": "这个订单的实付金额是多少", "intent": "QUERY", "scenario": "payment_amount", "slots": {}, "expected_response": "提供订单实际支付金额"},
    {"query": "我想延长收货时间", "intent": "QUERY", "scenario": "extend_receipt", "slots": {}, "expected_response": "确认是否支持延长收货"},
    {"query": "订单已经交易成功了还能退货吗", "intent": "REFUND", "scenario": "post_completion_refund", "slots": {}, "expected_response": "说明交易成功后退货政策"},
    {"query": "帮我查下订单的支付时间", "intent": "QUERY", "scenario": "payment_time", "slots": {}, "expected_response": "提供订单支付时间信息"},
    {"query": "这个订单的优惠券还能退回来吗", "intent": "REFUND", "scenario": "coupon_refund", "slots": {}, "expected_response": "说明优惠券退还规则"},
    {"query": "我误删了订单还能恢复吗", "intent": "QUERY", "scenario": "recover_order", "slots": {}, "expected_response": "确认是否支持订单恢复"},
    {"query": "帮我查询订单 SN2024444 的退款状态", "intent": "REFUND", "scenario": "refund_tracking", "slots": {"order_sn": "SN2024444"}, "expected_response": "查询退款处理状态和进度"},
    {"query": "订单显示已完成但我没收到货", "intent": "QUERY", "scenario": "completed_not_received", "slots": {}, "expected_response": "核实订单状态并启动调查"},
    {"query": "我想投诉订单问题", "intent": "REFUND", "scenario": "complaint_order", "slots": {}, "expected_response": "引导用户提交投诉"},
    {"query": "这个订单的物流单号是多少", "intent": "QUERY", "scenario": "tracking_number", "slots": {}, "expected_response": "提供物流单号信息"},
    {"query": "帮我看看有哪些订单还没评价", "intent": "QUERY", "scenario": "unreviewed_orders", "slots": {}, "expected_response": "列出待评价订单"},
    {"query": "订单里的赠品没收到", "intent": "QUERY", "scenario": "missing_gift", "slots": {}, "expected_response": "核实赠品发货情况"},
    {"query": "我买了两件只收到一件", "intent": "QUERY", "scenario": "missing_item", "slots": {}, "expected_response": "核实订单商品数量并处理"},
    {"query": "订单价格降了能退差价吗", "intent": "REFUND", "scenario": "price_protection", "slots": {}, "expected_response": "说明保价政策"},
    {"query": "帮我查一下去年双11的订单", "intent": "QUERY", "scenario": "historical_event", "slots": {}, "expected_response": "按活动查询历史订单"},
    {"query": "这个订单能开发票吗", "intent": "QUERY", "scenario": "invoice_eligibility", "slots": {}, "expected_response": "确认发票开具资格"},
    {"query": "订单取消后钱什么时候退回来", "intent": "REFUND", "scenario": "refund_timeline", "slots": {}, "expected_response": "说明退款到账时间"},
    {"query": "我想把订单转送给别人", "intent": "QUERY", "scenario": "gift_transfer", "slots": {}, "expected_response": "确认是否支持订单转赠"},
    {"query": "帮我查下订单的优惠信息", "intent": "QUERY", "scenario": "discount_details", "slots": {}, "expected_response": "列出订单使用的优惠"},
    {"query": "订单里有个商品发错货了", "intent": "REFUND", "scenario": "wrong_item", "slots": {}, "expected_response": "处理发错货问题"},
    {"query": "我重复下单了能取消一个吗", "intent": "QUERY", "scenario": "duplicate_order", "slots": {}, "expected_response": "协助取消重复订单"},
    {"query": "帮我催一下订单发货", "intent": "QUERY", "scenario": "urge_shipment", "slots": {}, "expected_response": "联系仓库催促发货"},
    {"query": "这个订单的会员积分是多少", "intent": "QUERY", "scenario": "member_points", "slots": {}, "expected_response": "提供订单积分信息"},
    {"query": "订单已经退款了为什么还没到账", "intent": "REFUND", "scenario": "refund_not_received", "slots": {}, "expected_response": "查询退款状态和到账时间"},
    {"query": "我想把已签收的商品退回去", "intent": "REFUND", "scenario": "return_after_receipt", "slots": {}, "expected_response": "处理已签收商品退货"},
    {"query": "帮我查下订单的售后记录", "intent": "QUERY", "scenario": "after_sales_history", "slots": {}, "expected_response": "查询订单售后历史"},
    {"query": "这个订单支持7天无理由退货吗", "intent": "REFUND", "scenario": "return_policy", "slots": {}, "expected_response": "说明退货政策"},
    {"query": "订单里有预售商品什么时候发", "intent": "QUERY", "scenario": "preorder_shipment", "slots": {}, "expected_response": "说明预售商品发货时间"},
    {"query": "帮我看下订单的物流轨迹", "intent": "QUERY", "scenario": "tracking_history", "slots": {}, "expected_response": "提供完整物流轨迹"},
]

# ---------------------------------------------------------------------------
# Policy Agent Examples
# ---------------------------------------------------------------------------

POLICY_EXAMPLES = [
    {"query": "运费是怎么计算的", "policy_category": "shipping", "expected_response": "说明运费计算规则", "sources": ["shipping_policy.md"]},
    {"query": "退换货政策是什么", "policy_category": "return", "expected_response": "说明退换货条件和流程", "sources": ["return_policy.md"]},
    {"query": "会员有什么权益", "policy_category": "membership", "expected_response": "说明会员等级和权益", "sources": ["membership_policy.md"]},
    {"query": "隐私政策怎么规定的", "policy_category": "privacy", "expected_response": "说明隐私保护政策", "sources": ["privacy_policy.md"]},
    {"query": "优惠券使用规则是什么", "policy_category": "promotion", "expected_response": "说明优惠券使用条件", "sources": ["coupon_policy.md"]},
    {"query": "积分怎么获得和使用", "policy_category": "points", "expected_response": "说明积分获取和使用规则", "sources": ["points_policy.md"]},
    {"query": "商品质量保证多久", "policy_category": "warranty", "expected_response": "说明质保期限和范围", "sources": ["warranty_policy.md"]},
    {"query": "订单取消规则是什么", "policy_category": "order", "expected_response": "说明订单取消条件和手续费", "sources": ["order_policy.md"]},
    {"query": "支付方式有哪些", "policy_category": "payment", "expected_response": "说明支持的支付方式", "sources": ["payment_policy.md"]},
    {"query": "发货时间一般多久", "policy_category": "shipping", "expected_response": "说明标准发货时效", "sources": ["shipping_policy.md"]},
    {"query": "海外购税费怎么算", "policy_category": "tax", "expected_response": "说明跨境税费政策", "sources": ["cross_border_policy.md"]},
    {"query": "商品不满意能退吗", "policy_category": "return", "expected_response": "说明无理由退货政策", "sources": ["return_policy.md"]},
    {"query": "价格保护政策是什么", "policy_category": "price", "expected_response": "说明保价规则和期限", "sources": ["price_policy.md"]},
    {"query": "账号被盗了怎么办", "policy_category": "security", "expected_response": "说明账号安全处理流程", "sources": ["security_policy.md"]},
    {"query": "如何申请发票", "policy_category": "invoice", "expected_response": "说明发票申请流程", "sources": ["invoice_policy.md"]},
    {"query": "预售商品规则", "policy_category": "preorder", "expected_response": "说明预售商品发货和退款规则", "sources": ["preorder_policy.md"]},
    {"query": "抢购活动规则", "policy_category": "promotion", "expected_response": "说明秒杀和抢购规则", "sources": ["flash_sale_policy.md"]},
    {"query": "售后服务政策", "policy_category": "service", "expected_response": "说明售后服务范围和流程", "sources": ["after_sales_policy.md"]},
    {"query": "商品损坏怎么赔偿", "policy_category": "compensation", "expected_response": "说明商品损坏赔偿标准", "sources": ["damage_policy.md"]},
    {"query": "退款多久到账", "policy_category": "refund", "expected_response": "说明退款处理时效", "sources": ["refund_policy.md"]},
    {"query": "如何修改收货地址", "policy_category": "order", "expected_response": "说明地址修改规则和时限", "sources": ["order_policy.md"]},
    {"query": "物流延误怎么赔偿", "policy_category": "shipping", "expected_response": "说明物流延误补偿政策", "sources": ["shipping_policy.md"]},
    {"query": "七天无理由退货条件", "policy_category": "return", "expected_response": "详细说明7天无理由退货条件", "sources": ["return_policy.md"]},
    {"query": "定制商品能退吗", "policy_category": "return", "expected_response": "说明定制商品退货政策", "sources": ["custom_product_policy.md"]},
    {"query": "生鲜商品售后政策", "policy_category": "return", "expected_response": "说明生鲜商品售后规则", "sources": ["fresh_product_policy.md"]},
    {"query": "满减活动规则", "policy_category": "promotion", "expected_response": "说明满减活动参与条件", "sources": ["promotion_policy.md"]},
    {"query": "新人专享优惠", "policy_category": "promotion", "expected_response": "说明新用户优惠政策", "sources": ["new_user_policy.md"]},
    {"query": "企业采购政策", "policy_category": "b2b", "expected_response": "说明企业采购优惠和流程", "sources": ["b2b_policy.md"]},
    {"query": "拼团活动规则", "policy_category": "promotion", "expected_response": "说明拼团规则和要求", "sources": ["group_buy_policy.md"]},
    {"query": "以旧换新政策", "policy_category": "trade_in", "expected_response": "说明以旧换新流程和补贴", "sources": ["trade_in_policy.md"]},
    {"query": "延保服务说明", "policy_category": "warranty", "expected_response": "说明延保服务内容和价格", "sources": ["extended_warranty.md"]},
    {"query": "上门安装政策", "policy_category": "service", "expected_response": "说明上门安装范围和费用", "sources": ["installation_policy.md"]},
    {"query": "评价规则", "policy_category": "review", "expected_response": "说明评价发布规则", "sources": ["review_policy.md"]},
    {"query": "举报投诉流程", "policy_category": "complaint", "expected_response": "说明投诉处理流程", "sources": ["complaint_policy.md"]},
    {"query": "数据安全政策", "policy_category": "privacy", "expected_response": "说明数据保护措施", "sources": ["data_security_policy.md"]},
    {"query": "未成年人购物规定", "policy_category": "legal", "expected_response": "说明未成年人购物限制", "sources": ["minor_policy.md"]},
    {"query": "禁售商品清单", "policy_category": "legal", "expected_response": "说明平台禁售商品范围", "sources": ["prohibited_items.md"]},
    {"query": "知识产权投诉", "policy_category": "legal", "expected_response": "说明知识产权投诉流程", "sources": ["ip_complaint_policy.md"]},
    {"query": "平台交易规则", "policy_category": "legal", "expected_response": "说明平台基本交易规则", "sources": ["trading_rules.md"]},
    {"query": "用户行为规范", "policy_category": "legal", "expected_response": "说明用户行为准则", "sources": ["user_conduct.md"]},
    {"query": "商家入驻标准", "policy_category": "merchant", "expected_response": "说明商家入驻条件", "sources": ["merchant_policy.md"]},
    {"query": "平台服务费说明", "policy_category": "merchant", "expected_response": "说明平台服务费用", "sources": ["service_fee_policy.md"]},
    {"query": "保证金规则", "policy_category": "merchant", "expected_response": "说明保证金缴纳和退还", "sources": ["deposit_policy.md"]},
    {"query": "虚假发货处罚", "policy_category": "merchant", "expected_response": "说明虚假发货定义和处罚", "sources": ["penalty_policy.md"]},
    {"query": "商品发布规范", "policy_category": "merchant", "expected_response": "说明商品发布要求", "sources": ["listing_policy.md"]},
    {"query": "促销活动报名", "policy_category": "promotion", "expected_response": "说明活动报名条件和流程", "sources": ["campaign_policy.md"]},
    {"query": "店铺评分规则", "policy_category": "merchant", "expected_response": "说明店铺评分计算方式", "sources": ["rating_policy.md"]},
    {"query": "客服响应时效", "policy_category": "service", "expected_response": "说明客服响应时间要求", "sources": ["service_sla.md"]},
    {"query": "纠纷处理规则", "policy_category": "dispute", "expected_response": "说明交易纠纷处理流程", "sources": ["dispute_policy.md"]},
    {"query": "赔偿标准说明", "policy_category": "compensation", "expected_response": "说明各类赔偿标准", "sources": ["compensation_standard.md"]},
    {"query": "不可抗力处理", "policy_category": "legal", "expected_response": "说明不可抗力情况处理", "sources": ["force_majeure.md"]},
]

# ---------------------------------------------------------------------------
# Product Agent Examples
# ---------------------------------------------------------------------------

PRODUCT_EXAMPLES = [
    {"query": "这款手机有什么颜色", "intent": "product_info", "product_type": "electronics", "expected_response": "提供手机颜色选项"},
    {"query": "这件衣服尺码怎么选", "intent": "size_guide", "product_type": "clothing", "expected_response": "提供尺码选择建议"},
    {"query": "这个商品有优惠券吗", "intent": "promotion", "product_type": "general", "expected_response": "查询可用优惠券"},
    {"query": "帮我找下类似商品", "intent": "similar_products", "product_type": "general", "expected_response": "推荐相似商品"},
    {"query": "这款笔记本配置怎么样", "intent": "product_specs", "product_type": "electronics", "expected_response": "详细介绍产品配置"},
    {"query": "这个商品评价怎么样", "intent": "reviews", "product_type": "general", "expected_response": "总结用户评价"},
    {"query": "有更大容量的吗", "intent": "variant", "product_type": "general", "expected_response": "推荐大容量版本"},
    {"query": "这个商品什么时候有货", "intent": "availability", "product_type": "general", "expected_response": "查询库存和补货时间"},
    {"query": "帮我对比这两款手机", "intent": "comparison", "product_type": "electronics", "expected_response": "对比两款产品参数"},
    {"query": "这个护肤品适合敏感肌吗", "intent": "suitability", "product_type": "beauty", "expected_response": "说明适用肤质"},
    {"query": "这个商品的材质是什么", "intent": "product_info", "product_type": "general", "expected_response": "说明产品材质"},
    {"query": "有配套商品推荐吗", "intent": "accessories", "product_type": "general", "expected_response": "推荐配套商品"},
    {"query": "这个商品怎么使用", "intent": "usage", "product_type": "general", "expected_response": "提供使用说明"},
    {"query": "这款相机支持4K吗", "intent": "product_specs", "product_type": "electronics", "expected_response": "确认4K支持情况"},
    {"query": "这个商品的保修多久", "intent": "warranty", "product_type": "general", "expected_response": "说明保修期限"},
    {"query": "有学生优惠吗", "intent": "promotion", "product_type": "general", "expected_response": "查询学生优惠政策"},
    {"query": "这个商品能分期吗", "intent": "payment", "product_type": "general", "expected_response": "说明分期付款选项"},
    {"query": "帮我找下性价比高的耳机", "intent": "recommendation", "product_type": "electronics", "expected_response": "推荐高性价比耳机"},
    {"query": "这个商品支持7天无理由吗", "intent": "policy", "product_type": "general", "expected_response": "确认退货政策"},
    {"query": "这款洗面奶成分安全吗", "intent": "safety", "product_type": "beauty", "expected_response": "说明成分安全性"},
    {"query": "这个商品有没有假货", "intent": "authenticity", "product_type": "general", "expected_response": "保证正品并说明验证方式"},
    {"query": "帮我推荐一款适合送礼的", "intent": "recommendation", "product_type": "general", "expected_response": "推荐适合送礼的商品"},
    {"query": "这个商品的重量是多少", "intent": "product_specs", "product_type": "general", "expected_response": "提供商品重量信息"},
    {"query": "有进口版本吗", "intent": "variant", "product_type": "general", "expected_response": "查询进口版本信息"},
    {"query": "这个商品怎么保养", "intent": "maintenance", "product_type": "general", "expected_response": "提供保养建议"},
    {"query": "这款跑鞋适合马拉松吗", "intent": "suitability", "product_type": "sports", "expected_response": "说明适用场景"},
    {"query": "这个商品的产地是哪里", "intent": "product_info", "product_type": "general", "expected_response": "说明商品产地"},
    {"query": "有试用装吗", "intent": "variant", "product_type": "beauty", "expected_response": "查询试用装信息"},
    {"query": "这个商品的历史最低价", "intent": "price_history", "product_type": "general", "expected_response": "提供价格走势信息"},
    {"query": "帮我看看这款商品的差评", "intent": "reviews", "product_type": "general", "expected_response": "总结负面评价"},
    {"query": "这个商品适合什么年龄段", "intent": "suitability", "product_type": "general", "expected_response": "说明适用年龄范围"},
    {"query": "有套装优惠吗", "intent": "promotion", "product_type": "general", "expected_response": "查询套装优惠信息"},
    {"query": "这个商品包邮吗", "intent": "shipping", "product_type": "general", "expected_response": "说明运费政策"},
    {"query": "帮我对比下不同品牌的", "intent": "comparison", "product_type": "general", "expected_response": "对比不同品牌产品"},
    {"query": "这个商品有环保认证吗", "intent": "certification", "product_type": "general", "expected_response": "说明环保认证情况"},
    {"query": "这款护肤品孕妇能用吗", "intent": "safety", "product_type": "beauty", "expected_response": "确认孕妇使用安全性"},
    {"query": "这个商品怎么安装", "intent": "usage", "product_type": "general", "expected_response": "提供安装指南"},
    {"query": "有以旧换新活动吗", "intent": "promotion", "product_type": "electronics", "expected_response": "查询以旧换新政策"},
    {"query": "这个商品的续航多久", "intent": "product_specs", "product_type": "electronics", "expected_response": "说明续航能力"},
    {"query": "帮我推荐入门款", "intent": "recommendation", "product_type": "general", "expected_response": "推荐入门级产品"},
    {"query": "这个商品支持退换吗", "intent": "policy", "product_type": "general", "expected_response": "说明退换货政策"},
    {"query": "有赠品吗", "intent": "promotion", "product_type": "general", "expected_response": "查询赠品活动"},
    {"query": "这款商品的防水等级", "intent": "product_specs", "product_type": "electronics", "expected_response": "说明防水等级"},
    {"query": "帮我找下新品", "intent": "recommendation", "product_type": "general", "expected_response": "推荐最新上市商品"},
    {"query": "这个商品的充电时间多久", "intent": "product_specs", "product_type": "electronics", "expected_response": "说明充电时长"},
    {"query": "有企业采购价吗", "intent": "promotion", "product_type": "general", "expected_response": "说明企业采购优惠"},
    {"query": "这个商品的存储容量", "intent": "product_specs", "product_type": "electronics", "expected_response": "说明存储容量选项"},
    {"query": "帮我看看买家秀", "intent": "reviews", "product_type": "general", "expected_response": "展示买家评价图片"},
    {"query": "这个商品支持全球联保吗", "intent": "warranty", "product_type": "electronics", "expected_response": "说明保修范围"},
]

# ---------------------------------------------------------------------------
# Payment Agent Examples
# ---------------------------------------------------------------------------

PAYMENT_EXAMPLES = [
    {"query": "支持哪些支付方式", "intent": "payment_methods", "expected_response": "列出支持的支付方式"},
    {"query": "怎么绑定银行卡", "intent": "bind_card", "expected_response": "提供绑卡流程"},
    {"query": "支付失败了怎么办", "intent": "payment_issue", "expected_response": "排查支付失败原因"},
    {"query": "能分期付款吗", "intent": "installment", "expected_response": "说明分期选项"},
    {"query": "怎么修改支付密码", "intent": "security", "expected_response": "提供修改密码流程"},
    {"query": "余额怎么充值", "intent": "recharge", "expected_response": "说明充值方式"},
    {"query": "退款到哪里了", "intent": "refund_status", "expected_response": "查询退款去向"},
    {"query": "怎么开通免密支付", "intent": "quick_pay", "expected_response": "说明开通流程"},
    {"query": "支付限额是多少", "intent": "limits", "expected_response": "说明支付限额"},
    {"query": "怎么取消自动扣款", "intent": "auto_pay", "expected_response": "提供取消流程"},
    {"query": "支持花呗吗", "intent": "payment_methods", "expected_response": "确认花呗支持情况"},
    {"query": "怎么申请发票", "intent": "invoice", "expected_response": "提供开票流程"},
    {"query": "余额提现多久到账", "intent": "withdrawal", "expected_response": "说明提现时效"},
    {"query": "支付时提示风控怎么办", "intent": "security", "expected_response": "解决风控限制"},
    {"query": "能使用微信支付吗", "intent": "payment_methods", "expected_response": "确认微信支付支持"},
    {"query": "怎么查看支付记录", "intent": "history", "expected_response": "提供查询路径"},
    {"query": "银行卡支付有优惠吗", "intent": "promotion", "expected_response": "查询银行卡优惠"},
    {"query": "怎么解绑银行卡", "intent": "bind_card", "expected_response": "提供解绑流程"},
    {"query": "支付密码忘了怎么办", "intent": "security", "expected_response": "提供密码重置流程"},
    {"query": "支持信用卡支付吗", "intent": "payment_methods", "expected_response": "确认信用卡支持"},
    {"query": "为什么扣款了订单没生成", "intent": "payment_issue", "expected_response": "排查支付异常"},
    {"query": "怎么设置支付提醒", "intent": "notification", "expected_response": "说明提醒设置"},
    {"query": "余额可以转账吗", "intent": "transfer", "expected_response": "说明转账规则"},
    {"query": "代付功能怎么用", "intent": "payment_methods", "expected_response": "说明代付流程"},
    {"query": "支付时验证码收不到", "intent": "payment_issue", "expected_response": "解决验证码问题"},
    {"query": "怎么查看账单明细", "intent": "history", "expected_response": "提供账单查询方式"},
    {"query": "支持外币支付吗", "intent": "payment_methods", "expected_response": "确认外币支付支持"},
    {"query": "怎么关闭余额支付", "intent": "security", "expected_response": "提供关闭流程"},
    {"query": "支付时提示余额不足", "intent": "payment_issue", "expected_response": "建议充值或换支付方式"},
    {"query": "怎么申请企业发票", "intent": "invoice", "expected_response": "说明企业开票流程"},
    {"query": "退款退到原支付渠道吗", "intent": "refund_status", "expected_response": "说明退款路径"},
    {"query": "怎么绑定信用卡", "intent": "bind_card", "expected_response": "提供绑卡流程"},
    {"query": "支付安全保障有哪些", "intent": "security", "expected_response": "说明安全措施"},
    {"query": "怎么修改默认支付方式", "intent": "payment_methods", "expected_response": "提供修改方式"},
    {"query": "分期手续费多少", "intent": "installment", "expected_response": "说明分期费率"},
    {"query": "怎么提前还清分期", "intent": "installment", "expected_response": "提供提前还款流程"},
    {"query": "支付时网络中断怎么办", "intent": "payment_issue", "expected_response": "处理网络中断情况"},
    {"query": "怎么查看优惠券", "intent": "promotion", "expected_response": "提供优惠券查询路径"},
    {"query": "支持Apple Pay吗", "intent": "payment_methods", "expected_response": "确认Apple Pay支持"},
    {"query": "怎么取消待支付订单", "intent": "order", "expected_response": "提供取消流程"},
    {"query": "余额可以提现到微信吗", "intent": "withdrawal", "expected_response": "说明提现渠道"},
    {"query": "支付时提示银行卡过期", "intent": "payment_issue", "expected_response": "建议更新银行卡"},
    {"query": "怎么开通指纹支付", "intent": "quick_pay", "expected_response": "说明开通流程"},
    {"query": "支持云闪付吗", "intent": "payment_methods", "expected_response": "确认云闪付支持"},
    {"query": "怎么查询退款记录", "intent": "refund_status", "expected_response": "提供查询路径"},
    {"query": "支付密码输错被锁了", "intent": "security", "expected_response": "提供解锁流程"},
    {"query": "怎么设置小额免密", "intent": "quick_pay", "expected_response": "说明设置方式"},
    {"query": "支持数字人民币吗", "intent": "payment_methods", "expected_response": "确认数字人民币支持"},
    {"query": "怎么查看支付安全日志", "intent": "security", "expected_response": "提供查询路径"},
]

# ---------------------------------------------------------------------------
# Account Agent Examples
# ---------------------------------------------------------------------------

ACCOUNT_EXAMPLES = [
    {"query": "怎么修改手机号", "intent": "update_profile", "expected_response": "提供修改手机号流程"},
    {"query": "忘记密码了怎么办", "intent": "security", "expected_response": "提供密码重置流程"},
    {"query": "怎么注销账号", "intent": "account_management", "expected_response": "说明注销流程"},
    {"query": "实名认证怎么弄", "intent": "verification", "expected_response": "提供实名认证步骤"},
    {"query": "怎么查看会员等级", "intent": "membership", "expected_response": "显示会员等级信息"},
    {"query": "积分怎么兑换", "intent": "points", "expected_response": "说明积分兑换方式"},
    {"query": "怎么修改收货地址", "intent": "update_profile", "expected_response": "提供地址修改流程"},
    {"query": "账号被盗了怎么办", "intent": "security", "expected_response": "提供账号恢复流程"},
    {"query": "怎么绑定邮箱", "intent": "update_profile", "expected_response": "提供邮箱绑定流程"},
    {"query": "如何升级会员", "intent": "membership", "expected_response": "说明升级条件"},
    {"query": "怎么查看消费记录", "intent": "history", "expected_response": "提供查询路径"},
    {"query": "怎么解绑第三方账号", "intent": "account_management", "expected_response": "提供解绑流程"},
    {"query": "可以更换实名信息吗", "intent": "verification", "expected_response": "说明实名信息修改规则"},
    {"query": "怎么修改头像", "intent": "update_profile", "expected_response": "提供头像修改方式"},
    {"query": "会员到期怎么续费", "intent": "membership", "expected_response": "提供续费方式"},
    {"query": "怎么设置登录保护", "intent": "security", "expected_response": "说明安全设置选项"},
    {"query": "怎么查看优惠券", "intent": "history", "expected_response": "提供优惠券查看路径"},
    {"query": "账号被冻结了怎么办", "intent": "security", "expected_response": "提供解冻流程"},
    {"query": "怎么修改昵称", "intent": "update_profile", "expected_response": "提供昵称修改流程"},
    {"query": "如何设置支付密码", "intent": "security", "expected_response": "提供设置流程"},
    {"query": "怎么查看成长值", "intent": "membership", "expected_response": "显示成长值信息"},
    {"query": "可以合并多个账号吗", "intent": "account_management", "expected_response": "说明账号合并政策"},
    {"query": "怎么关闭消息推送", "intent": "preferences", "expected_response": "提供推送设置路径"},
    {"query": "怎么绑定微信", "intent": "update_profile", "expected_response": "提供微信绑定流程"},
    {"query": "账号异常登录提醒", "intent": "security", "expected_response": "说明异常登录处理"},
    {"query": "怎么修改登录密码", "intent": "security", "expected_response": "提供密码修改流程"},
    {"query": "如何查看账号安全等级", "intent": "security", "expected_response": "显示安全等级评估"},
    {"query": "怎么设置常用地址", "intent": "update_profile", "expected_response": "提供地址管理功能"},
    {"query": "会员权益有哪些", "intent": "membership", "expected_response": "列出会员权益"},
    {"query": "怎么查看浏览历史", "intent": "history", "expected_response": "提供浏览记录查看"},
    {"query": "账号可以转让吗", "intent": "account_management", "expected_response": "说明账号转让政策"},
    {"query": "怎么开启双重验证", "intent": "security", "expected_response": "提供2FA设置流程"},
    {"query": "怎么删除浏览记录", "intent": "preferences", "expected_response": "提供删除方式"},
    {"query": "如何查看账号注册时间", "intent": "history", "expected_response": "显示注册时间"},
    {"query": "怎么修改性别信息", "intent": "update_profile", "expected_response": "提供信息修改路径"},
    {"query": "积分会过期吗", "intent": "points", "expected_response": "说明积分有效期"},
    {"query": "怎么绑定QQ", "intent": "update_profile", "expected_response": "提供QQ绑定流程"},
    {"query": "怎么查看登录设备", "intent": "security", "expected_response": "提供设备管理功能"},
    {"query": "账号可以改名吗", "intent": "update_profile", "expected_response": "说明用户名修改规则"},
    {"query": "怎么退出其他设备登录", "intent": "security", "expected_response": "提供远程退出功能"},
    {"query": "如何查看账号信用分", "intent": "membership", "expected_response": "显示信用分信息"},
    {"query": "怎么开启指纹登录", "intent": "security", "expected_response": "提供指纹登录设置"},
    {"query": "怎么查看收藏商品", "intent": "history", "expected_response": "提供收藏夹查看"},
    {"query": "账号申诉流程", "intent": "security", "expected_response": "说明申诉流程"},
    {"query": "怎么设置生日", "intent": "update_profile", "expected_response": "提供生日设置路径"},
    {"query": "如何查看账号状态", "intent": "account_management", "expected_response": "显示账号状态信息"},
    {"query": "怎么修改地区", "intent": "update_profile", "expected_response": "提供地区修改方式"},
]

# ---------------------------------------------------------------------------
# Cart Agent Examples
# ---------------------------------------------------------------------------

CART_EXAMPLES = [
    {"query": "帮我看下购物车", "intent": "view_cart", "expected_response": "显示购物车商品列表"},
    {"query": "怎么添加商品到购物车", "intent": "add_item", "expected_response": "说明添加方式"},
    {"query": "购物车商品怎么删除", "intent": "remove_item", "expected_response": "提供删除操作步骤"},
    {"query": "怎么修改购买数量", "intent": "update_quantity", "expected_response": "提供数量修改方式"},
    {"query": "购物车里的商品失效了", "intent": "invalid_item", "expected_response": "解释失效原因"},
    {"query": "怎么清空购物车", "intent": "clear_cart", "expected_response": "提供清空操作"},
    {"query": "购物车商品降价了", "intent": "price_change", "expected_response": "说明价格保护"},
    {"query": "怎么合并结算", "intent": "checkout", "expected_response": "提供合并结算方式"},
    {"query": "购物车有数量限制吗", "intent": "limits", "expected_response": "说明数量限制"},
    {"query": "怎么收藏购物车商品", "intent": "save_for_later", "expected_response": "提供收藏方式"},
    {"query": "购物车商品能保存多久", "intent": "expiration", "expected_response": "说明保存期限"},
    {"query": "怎么查看购物车优惠", "intent": "promotions", "expected_response": "显示可用优惠"},
    {"query": "购物车怎么全选", "intent": "select_all", "expected_response": "提供全选操作"},
    {"query": "怎么移动商品到收藏夹", "intent": "save_for_later", "expected_response": "提供移动方式"},
    {"query": "购物车结算时库存不足", "intent": "stock_issue", "expected_response": "处理库存不足"},
    {"query": "怎么按店铺筛选购物车", "intent": "filter", "expected_response": "提供筛选方式"},
    {"query": "购物车支持凑单吗", "intent": "promotions", "expected_response": "说明凑单功能"},
    {"query": "怎么查看商品规格", "intent": "view_details", "expected_response": "显示商品规格"},
    {"query": "购物车商品可以对比吗", "intent": "compare", "expected_response": "说明对比功能"},
    {"query": "怎么分享购物车", "intent": "share", "expected_response": "提供分享方式"},
    {"query": "购物车 total 怎么计算", "intent": "price_calculation", "expected_response": "解释价格计算"},
    {"query": "怎么批量删除", "intent": "remove_item", "expected_response": "提供批量操作"},
    {"query": "购物车商品可以移回浏览吗", "intent": "save_for_later", "expected_response": "说明移回方式"},
    {"query": "怎么查看失效商品", "intent": "invalid_item", "expected_response": "显示失效商品列表"},
    {"query": "购物车支持多地址吗", "intent": "checkout", "expected_response": "说明多地址配送"},
    {"query": "怎么快速结算", "intent": "checkout", "expected_response": "提供快速结算方式"},
    {"query": "购物车能导入清单吗", "intent": "import", "expected_response": "说明导入功能"},
    {"query": "怎么查看相似商品", "intent": "recommendations", "expected_response": "推荐相似商品"},
    {"query": "购物车支持定时购吗", "intent": "checkout", "expected_response": "说明定时购功能"},
    {"query": "怎么查看历史购物车", "intent": "history", "expected_response": "提供历史记录"},
    {"query": "购物车商品可以预售吗", "intent": "preorder", "expected_response": "说明预售规则"},
    {"query": "怎么设置默认地址", "intent": "checkout", "expected_response": "提供默认地址设置"},
    {"query": "购物车怎么结算选中的", "intent": "checkout", "expected_response": "结算选中商品"},
    {"query": "怎么查看运费", "intent": "shipping", "expected_response": "显示运费信息"},
    {"query": "购物车支持优惠券叠加吗", "intent": "promotions", "expected_response": "说明叠加规则"},
    {"query": "怎么查看商品库存", "intent": "stock", "expected_response": "显示库存状态"},
    {"query": "购物车怎么收藏店铺", "intent": "favorites", "expected_response": "提供收藏方式"},
    {"query": "怎么设置购买提醒", "intent": "notifications", "expected_response": "提供提醒设置"},
    {"query": "购物车能开发票吗", "intent": "invoice", "expected_response": "说明开票方式"},
    {"query": "怎么查看购物车总重量", "intent": "shipping", "expected_response": "显示重量信息"},
    {"query": "购物车支持以旧换新吗", "intent": "trade_in", "expected_response": "说明以旧换新"},
    {"query": "怎么查看商品评价", "intent": "reviews", "expected_response": "提供评价查看"},
    {"query": "购物车能分期结算吗", "intent": "checkout", "expected_response": "说明分期结算"},
    {"query": "怎么查看赠品", "intent": "promotions", "expected_response": "显示赠品信息"},
    {"query": "购物车支持企业采购吗", "intent": "b2b", "expected_response": "说明企业采购"},
    {"query": "怎么查看预计送达时间", "intent": "shipping", "expected_response": "显示预计时间"},
    {"query": "购物车商品可以预约配送吗", "intent": "delivery", "expected_response": "说明预约配送"},
    {"query": "怎么查看商品详情", "intent": "view_details", "expected_response": "提供详情查看"},
    {"query": "购物车能导出清单吗", "intent": "export", "expected_response": "说明导出功能"},
    {"query": "怎么查看店铺优惠", "intent": "promotions", "expected_response": "显示店铺优惠"},
]

# ---------------------------------------------------------------------------
# Logistics Agent Examples
# ---------------------------------------------------------------------------

LOGISTICS_EXAMPLES = [
    {"query": "帮我查下快递到哪里了", "intent": "track", "expected_response": "提供物流跟踪信息"},
    {"query": "快递显示已签收但我没收到", "intent": "delivery_issue", "expected_response": "处理签收异常"},
    {"query": "怎么修改配送地址", "intent": "modify_address", "expected_response": "提供地址修改方式"},
    {"query": "配送时间可以指定吗", "intent": "delivery_time", "expected_response": "说明指定配送规则"},
    {"query": "快递延误了怎么办", "intent": "delay", "expected_response": "处理延误问题"},
    {"query": "怎么联系配送员", "intent": "contact_courier", "expected_response": "提供联系方式"},
    {"query": "支持自提吗", "intent": "pickup", "expected_response": "说明自提点信息"},
    {"query": "快递破损了怎么办", "intent": "damaged", "expected_response": "处理破损包裹"},
    {"query": "怎么预约配送时间", "intent": "schedule", "expected_response": "提供预约方式"},
    {"query": "物流信息显示异常", "intent": "tracking_issue", "expected_response": "排查物流异常"},
    {"query": "怎么拒收快递", "intent": "refuse", "expected_response": "提供拒收流程"},
    {"query": "快递丢了怎么办", "intent": "lost", "expected_response": "处理丢件问题"},
    {"query": "怎么查看配送进度", "intent": "track", "expected_response": "显示配送进度"},
    {"query": "支持货到付款吗", "intent": "cod", "expected_response": "确认货到付款支持"},
    {"query": "快递到了但我不在家", "intent": "missed_delivery", "expected_response": "处理未妥投"},
    {"query": "怎么投诉物流公司", "intent": "complaint", "expected_response": "提供投诉渠道"},
    {"query": "配送范围查询", "intent": "coverage", "expected_response": "显示配送范围"},
    {"query": "怎么查看运费明细", "intent": "shipping_cost", "expected_response": "显示运费计算"},
    {"query": "快递被退回怎么办", "intent": "returned", "expected_response": "处理退回件"},
    {"query": "怎么查询自提点", "intent": "pickup", "expected_response": "提供自提点查询"},
    {"query": "支持定时配送吗", "intent": "delivery_time", "expected_response": "说明定时配送"},
    {"query": "快递超重了怎么办", "intent": "overweight", "expected_response": "处理超重包裹"},
    {"query": "怎么查看配送员位置", "intent": "track", "expected_response": "显示实时位置"},
    {"query": "物流停滞了怎么办", "intent": "delay", "expected_response": "处理物流停滞"},
    {"query": "支持代收货吗", "intent": "proxy", "expected_response": "说明代收服务"},
    {"query": "怎么查看发货仓库", "intent": "warehouse", "expected_response": "显示发货仓信息"},
    {"query": "快递单号怎么查", "intent": "track", "expected_response": "提供查询方式"},
    {"query": "支持夜间配送吗", "intent": "delivery_time", "expected_response": "说明夜间配送"},
    {"query": "怎么申请物流赔偿", "intent": "compensation", "expected_response": "提供赔偿申请"},
    {"query": "物流信息不更新", "intent": "tracking_issue", "expected_response": "处理信息停滞"},
    {"query": "怎么修改收货人", "intent": "modify_address", "expected_response": "提供修改方式"},
    {"query": "支持预约安装吗", "intent": "installation", "expected_response": "说明安装服务"},
    {"query": "快递显示派送中多久到", "intent": "delivery_estimate", "expected_response": "提供预计时间"},
    {"query": "怎么查看历史物流", "intent": "history", "expected_response": "提供历史查询"},
    {"query": "支持物流保价吗", "intent": "insurance", "expected_response": "说明保价服务"},
    {"query": "快递被冒领了怎么办", "intent": "security", "expected_response": "处理冒领问题"},
    {"query": "怎么设置默认配送方式", "intent": "preferences", "expected_response": "提供设置方式"},
    {"query": "支持环保包装吗", "intent": "eco", "expected_response": "说明环保选项"},
    {"query": "物流费用怎么算", "intent": "shipping_cost", "expected_response": "解释计费规则"},
    {"query": "怎么查看配送时效", "intent": "delivery_estimate", "expected_response": "显示时效承诺"},
    {"query": "支持指定快递公司吗", "intent": "preferences", "expected_response": "说明快递公司选择"},
    {"query": "怎么查看包装清单", "intent": "packing", "expected_response": "显示商品清单"},
    {"query": "快递放驿站了怎么取", "intent": "pickup", "expected_response": "提供取件方式"},
    {"query": "支持开箱验货吗", "intent": "inspection", "expected_response": "说明验货规则"},
    {"query": "怎么查看退货物流", "intent": "return_track", "expected_response": "提供退货跟踪"},
    {"query": "物流投诉处理时效", "intent": "complaint", "expected_response": "说明处理时效"},
    {"query": "支持大件配送吗", "intent": "bulky", "expected_response": "说明大件配送"},
    {"query": "怎么查看配送评分", "intent": "rating", "expected_response": "显示配送评价"},
    {"query": "快递需要身份证吗", "intent": "verification", "expected_response": "说明身份证要求"},
    {"query": "怎么查看电子面单", "intent": "receipt", "expected_response": "提供电子面单"},
    {"query": "支持同城配送吗", "intent": "same_day", "expected_response": "说明同城配送"},
    {"query": "物流问题怎么联系客服", "intent": "support", "expected_response": "提供客服渠道"},
]

# ---------------------------------------------------------------------------
# Router Agent Examples
# ---------------------------------------------------------------------------

ROUTER_EXAMPLES = [
    {"query": "你好", "primary_intent": "GREETING", "expected_agent": "router", "expected_response": "友好问候"},
    {"query": "帮我查下订单", "primary_intent": "ORDER", "expected_agent": "order_agent", "expected_response": "转接订单Agent"},
    {"query": "运费怎么算", "primary_intent": "POLICY", "expected_agent": "policy_agent", "expected_response": "转接政策Agent"},
    {"query": "这款手机怎么样", "primary_intent": "PRODUCT", "expected_agent": "product_agent", "expected_response": "转接商品Agent"},
    {"query": "我想退货", "primary_intent": "AFTER_SALES", "expected_agent": "order_agent", "expected_response": "转接售后Agent"},
    {"query": "快递到哪了", "primary_intent": "LOGISTICS", "expected_agent": "logistics", "expected_response": "转接物流Agent"},
    {"query": "怎么修改密码", "primary_intent": "ACCOUNT", "expected_agent": "account", "expected_response": "转接账号Agent"},
    {"query": "怎么付款", "primary_intent": "PAYMENT", "expected_agent": "payment", "expected_response": "转接支付Agent"},
    {"query": "加入购物车", "primary_intent": "CART", "expected_agent": "cart", "expected_response": "转接购物车Agent"},
    {"query": "我要投诉", "primary_intent": "COMPLAINT", "expected_agent": "complaint", "expected_response": "转接投诉Agent"},
    {"query": "谢谢", "primary_intent": "GREETING", "expected_agent": "router", "expected_response": "礼貌回应"},
    {"query": "再见", "primary_intent": "GREETING", "expected_agent": "router", "expected_response": "礼貌告别"},
    {"query": "查订单 SN2024001", "primary_intent": "ORDER", "expected_agent": "order_agent", "expected_response": "转接订单Agent"},
    {"query": "退换货政策", "primary_intent": "POLICY", "expected_agent": "policy_agent", "expected_response": "转接政策Agent"},
    {"query": "有优惠券吗", "primary_intent": "PROMOTION", "expected_agent": "policy_agent", "expected_response": "转接政策Agent"},
    {"query": "怎么注册", "primary_intent": "ACCOUNT", "expected_agent": "account", "expected_response": "转接账号Agent"},
    {"query": "支持支付宝吗", "primary_intent": "PAYMENT", "expected_agent": "payment", "expected_response": "转接支付Agent"},
    {"query": "购物车结算", "primary_intent": "CART", "expected_agent": "cart", "expected_response": "转接购物车Agent"},
    {"query": "我要退款", "primary_intent": "AFTER_SALES", "expected_agent": "order_agent", "expected_response": "转接售后Agent"},
    {"query": "物流信息", "primary_intent": "LOGISTICS", "expected_agent": "logistics", "expected_response": "转接物流Agent"},
    {"query": "商品评价", "primary_intent": "PRODUCT", "expected_agent": "product_agent", "expected_response": "转接商品Agent"},
    {"query": "服务态度差", "primary_intent": "COMPLAINT", "expected_agent": "complaint", "expected_response": "转接投诉Agent"},
    {"query": "积分怎么用", "primary_intent": "POLICY", "expected_agent": "policy_agent", "expected_response": "转接政策Agent"},
    {"query": "会员权益", "primary_intent": "POLICY", "expected_agent": "policy_agent", "expected_response": "转接政策Agent"},
    {"query": "发票问题", "primary_intent": "PAYMENT", "expected_agent": "payment", "expected_response": "转接支付Agent"},
    {"query": "账号安全", "primary_intent": "ACCOUNT", "expected_agent": "account", "expected_response": "转接账号Agent"},
    {"query": "修改地址", "primary_intent": "ACCOUNT", "expected_agent": "account", "expected_response": "转接账号Agent"},
    {"query": "查看余额", "primary_intent": "PAYMENT", "expected_agent": "payment", "expected_response": "转接支付Agent"},
    {"query": "删除商品", "primary_intent": "CART", "expected_agent": "cart", "expected_response": "转接购物车Agent"},
    {"query": "催发货", "primary_intent": "ORDER", "expected_agent": "order_agent", "expected_response": "转接订单Agent"},
    {"query": "赔偿", "primary_intent": "COMPLAINT", "expected_agent": "complaint", "expected_response": "转接投诉Agent"},
    {"query": "活动规则", "primary_intent": "POLICY", "expected_agent": "policy_agent", "expected_response": "转接政策Agent"},
    {"query": "密码找回", "primary_intent": "ACCOUNT", "expected_agent": "account", "expected_response": "转接账号Agent"},
    {"query": "分期付款", "primary_intent": "PAYMENT", "expected_agent": "payment", "expected_response": "转接支付Agent"},
    {"query": "添加收藏", "primary_intent": "PRODUCT", "expected_agent": "product_agent", "expected_response": "转接商品Agent"},
    {"query": "清空购物车", "primary_intent": "CART", "expected_agent": "cart", "expected_response": "转接购物车Agent"},
    {"query": "物流投诉", "primary_intent": "COMPLAINT", "expected_agent": "complaint", "expected_response": "转接投诉Agent"},
    {"query": "订单取消", "primary_intent": "ORDER", "expected_agent": "order_agent", "expected_response": "转接订单Agent"},
    {"query": "尺码咨询", "primary_intent": "PRODUCT", "expected_agent": "product_agent", "expected_response": "转接商品Agent"},
    {"query": "优惠券使用", "primary_intent": "CART", "expected_agent": "cart", "expected_response": "转接购物车Agent"},
    {"query": "实名认证", "primary_intent": "ACCOUNT", "expected_agent": "account", "expected_response": "转接账号Agent"},
    {"query": "账户注销", "primary_intent": "ACCOUNT", "expected_agent": "account", "expected_response": "转接账号Agent"},
    {"query": "售后申请", "primary_intent": "AFTER_SALES", "expected_agent": "order_agent", "expected_response": "转接售后Agent"},
    {"query": "自提点查询", "primary_intent": "LOGISTICS", "expected_agent": "logistics", "expected_response": "转接物流Agent"},
    {"query": "配送时间", "primary_intent": "LOGISTICS", "expected_agent": "logistics", "expected_response": "转接物流Agent"},
    {"query": "新品推荐", "primary_intent": "PRODUCT", "expected_agent": "product_agent", "expected_response": "转接商品Agent"},
    {"query": "价格保护", "primary_intent": "POLICY", "expected_agent": "policy_agent", "expected_response": "转接政策Agent"},
    {"query": "支付方式", "primary_intent": "PAYMENT", "expected_agent": "payment", "expected_response": "转接支付Agent"},
    {"query": "修改数量", "primary_intent": "CART", "expected_agent": "cart", "expected_response": "转接购物车Agent"},
    {"query": "物流跟踪", "primary_intent": "LOGISTICS", "expected_agent": "logistics", "expected_response": "转接物流Agent"},
    {"query": "投诉进度", "primary_intent": "COMPLAINT", "expected_agent": "complaint", "expected_response": "转接投诉Agent"},
    {"query": "订单修改", "primary_intent": "ORDER", "expected_agent": "order_agent", "expected_response": "转接订单Agent"},
    {"query": "商品对比", "primary_intent": "PRODUCT", "expected_agent": "product_agent", "expected_response": "转接商品Agent"},
    {"query": "活动咨询", "primary_intent": "POLICY", "expected_agent": "policy_agent", "expected_response": "转接政策Agent"},
]


def main() -> None:
    """Generate all few-shot example files."""
    write_examples("order", ORDER_EXAMPLES)
    write_examples("policy", POLICY_EXAMPLES)
    write_examples("product", PRODUCT_EXAMPLES)
    write_examples("payment", PAYMENT_EXAMPLES)
    write_examples("account", ACCOUNT_EXAMPLES)
    write_examples("cart", CART_EXAMPLES)
    write_examples("logistics", LOGISTICS_EXAMPLES)
    write_examples("router", ROUTER_EXAMPLES)

    # Count total
    total = sum(len(examples) for examples in [
        ORDER_EXAMPLES, POLICY_EXAMPLES, PRODUCT_EXAMPLES,
        PAYMENT_EXAMPLES, ACCOUNT_EXAMPLES, CART_EXAMPLES,
        LOGISTICS_EXAMPLES, ROUTER_EXAMPLES,
    ])
    print(f"\nTotal examples created: {total}")


if __name__ == "__main__":
    main()
